'use strict';

/* ═══════════════════════════════════════════════════════════════════════
   Erie Canal Corridor — app.js
   Vanilla JS. No build step. Requires Mapbox GL JS v2 + PapaParse on page.
   ═══════════════════════════════════════════════════════════════════════ */

// ── 1. Configuration ─────────────────────────────────────────────────────────

const CONFIG = {
  token:  'pk.eyJ1Ijoic3N4bXkzMTYiLCJhIjoiY21vMmxzazJzMHZmNzJvcWEydWtzNXV5ZSJ9.OdqfxorKVhGtPdP1kVkTqA',
  style:  'mapbox://styles/mapbox/light-v11',
  center: [-76.1, 43.05],   // geographic center of Erie Canal corridor
  zoom:   7,
  minYear: 1820,
  maxYear: 2024,
  defaultYear: 1920
};

// Local data file paths (gitignored; generated by scripts/prepare_data.py)
const DATA_PATHS = {
  industry:      'data/industry_sites.csv',
  healthcare:    'data/healthcare_clean.csv',
  demographics:  'data/demographics.geojson',
  canal:         'data/canal_corridor.geojson'
};

// ── 2. Color maps ─────────────────────────────────────────────────────────────

const INDUSTRY_COLORS = {
  'manufacturing': '#e74c3c',
  'shipping':      '#2980b9',
  'milling':       '#f39c12',
  'textiles':      '#9b59b6',
  'agriculture':   '#27ae60',
  'mining':        '#7f8c8d',
  'ironworks':     '#c0392b',
  'commerce':      '#16a085',
  'other':         '#bdc3c7'
};

const HEALTHCARE_COLORS = {
  'hospital':      '#c0392b',
  'clinic':        '#2980b9',
  'urgent care':   '#e67e22',
  'nursing home':  '#8e44ad',
  'pharmacy':      '#27ae60',
  'mental health': '#16a085',
  'diagnostic':    '#d35400',
  'other':         '#7f8c8d'
};

// ── Case Study colors ─────────────────────────────────────────────────────────
// Two flat colors so industry vs healthcare are immediately distinguishable
// at city scale, where both layers overlap.
const CS_INDUSTRY_COLOR  = '#e67e22';   // warm orange  — industrial / historical
const CS_HEALTHCARE_COLOR = '#1abc9c';  // cool teal    — health / care

// ── Case Study: fixed city — Rochester, NY ────────────────────────────────────
// bbox: [minLng, minLat, maxLng, maxLat] — used to spatially filter industry sites.
// county: used to filter healthcare facilities from the CSV.

const CASE_STUDY_CITY = {
  name:   'Rochester',
  center: [-77.609, 43.157],
  zoom:   13,             // city-level zoom
  millLocation: [-77.6088, 43.1566],
  county: 'Monroe',
  bbox:   [-77.85, 43.05, -77.40, 43.30]
};

// Five-step color ramps for choropleth (low → high)
const CHOROPLETH_CONFIG = {
  median_age: {
    colors: ['#ffffcc', '#a1dab4', '#41b6c4', '#2c7fb8', '#253494'],
    label:  'Median Age (years)'
  },
  median_income: {
    colors: ['#f7fcf5', '#c7e9c0', '#74c476', '#238b45', '#00441b'],
    label:  'Median Household Income ($)'
  },
  population_density: {
    colors: ['#f7f4f9', '#d4b9da', '#df65b0', '#dd1c77', '#67001f'],
    label:  'Population Density (per sq mi)'
  }
};

// ── 3. Application state ──────────────────────────────────────────────────────

const state = {
  mode:            'industry',   // 'industry' | 'healthcare' | 'casestudy'
  year:            CONFIG.defaultYear,
  choroplethField: 'median_age',
  choroplethStats: {},           // computed after demographics load
  caseStudyFirstHealthcareYear: null,
  caseStudyZoomedToMill: false,
  loaded: {
    industry:     false,
    healthcare:   false,
    demographics: false,
    canal:        false
  },
  data: {
    industry:     null,
    healthcare:   null,
    demographics: null,
    canal:        null
  }
};

const STORY_CHAPTERS = {
  industry: {
    mode: 'industry',
    year: 1920,
    center: CONFIG.center,
    zoom: CONFIG.zoom,
    choroplethField: 'median_age',
    title: 'A corridor of change',
    description: 'The Erie Canal shaped upstate New York, connecting towns, farms, and factories. On this map the blue canal line is the backbone, while historic industry sites show how the corridor powered economic growth.',
    button: 'Show healthcare'
  },
  healthcare: {
    mode: 'healthcare',
    year: CONFIG.defaultYear,
    center: CONFIG.center,
    zoom: CONFIG.zoom,
    choroplethField: 'median_income',
    title: 'Health and the neighborhoods',
    description: 'Healthcare facilities are plotted against census tract shading. Compare communities by age, income, and population density to see where access and need overlap.',
    button: 'Show Rochester'
  },
  casestudy: {
    mode: 'casestudy',
    year: 1820,
    center: CASE_STUDY_CITY.center,
    zoom: CASE_STUDY_CITY.zoom,
    choroplethField: 'median_age',
    title: 'Rochester: city-scale story',
    description: 'Narrow into Monroe County and watch Rochester’s industrial roots and healthcare infrastructure come together in one focused case study. Start at the mill and then slide right as healthcare facilities arrive.',
    button: 'Restart story'
  }
};

let currentStoryChapter = 'industry';
const STORY_SEQUENCE = ['industry', 'healthcare', 'casestudy'];

function updateStoryCard(chapterId) {
  const chapter = STORY_CHAPTERS[chapterId];
  if (!chapter) return;
  document.getElementById('story-card-title').textContent = chapter.title;
  document.getElementById('story-card-copy').textContent = chapter.description;
  document.getElementById('story-cycle-btn').textContent = chapter.button;
}

function cycleStoryChapter() {
  const currentIndex = STORY_SEQUENCE.indexOf(currentStoryChapter);
  const nextIndex = (currentIndex + 1) % STORY_SEQUENCE.length;
  const nextChapter = STORY_SEQUENCE[nextIndex];
  goToStoryChapter(nextChapter);
}

function goToStoryChapter(chapterId) {
  const chapter = STORY_CHAPTERS[chapterId];
  if (!chapter) return;

  currentStoryChapter = chapterId;
  state.year = chapter.year;
  state.choroplethField = chapter.choroplethField;

  const slider = document.getElementById('timeline-slider');
  const yearDisplay = document.getElementById('current-year-display');
  if (slider) slider.value = String(state.year);
  if (yearDisplay) yearDisplay.textContent = String(state.year);

  const select = document.getElementById('choropleth-field');
  if (select) select.value = chapter.choroplethField;

  applyMode(chapter.mode, true);
  if (map.getLayer('demographics-fill')) {
    map.setPaintProperty('demographics-fill', 'fill-color', makeChoroplethPaint(state.choroplethField));
  }
  map.flyTo({ center: chapter.center, zoom: chapter.zoom, duration: 900 });
  updateStoryCard(chapterId);
}

function initStory() {
  const button = document.getElementById('story-cycle-btn');
  if (button) {
    button.addEventListener('click', cycleStoryChapter);
  }
  updateStoryCard(currentStoryChapter);
}

// ── 4. Map initialization ─────────────────────────────────────────────────────

mapboxgl.accessToken = CONFIG.token;

const map = new mapboxgl.Map({
  container:  'map',
  style:      CONFIG.style,
  center:     CONFIG.center,
  zoom:       CONFIG.zoom,
  projection: 'mercator'   // flat projection (no globe tilt)
});

map.addControl(new mapboxgl.NavigationControl({ showCompass: false }), 'top-left');
map.addControl(new mapboxgl.ScaleControl({ unit: 'imperial' }), 'bottom-left');

// ── 5. Data loading ───────────────────────────────────────────────────────────

/** Fetch a file; returns null (not throws) on 404/network failure. */
async function safeFetch(url) {
  try {
    const resp = await fetch(url);
    if (!resp.ok) return null;
    return resp;
  } catch {
    return null;
  }
}

/** Parse a CSV string into an array of row objects via PapaParse. */
function parseCSV(text) {
  const result = Papa.parse(text, { header: true, skipEmptyLines: true, dynamicTyping: true });
  return result.data;
}

/** Convert a flat CSV row array to a GeoJSON FeatureCollection. */
function csvToGeoJSON(rows, latField, lngField) {
  const features = [];
  for (const row of rows) {
    const lat = parseFloat(row[latField]);
    const lng = parseFloat(row[lngField]);
    if (isNaN(lat) || isNaN(lng)) continue;
    features.push({
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [lng, lat] },
      properties: { ...row }
    });
  }
  return { type: 'FeatureCollection', features };
}

async function loadAllData() {
  const missingFiles = [];

  // Industry sites (CSV)
  const industryResp = await safeFetch(DATA_PATHS.industry);
  if (industryResp) {
    const text = await industryResp.text();
    const rows = parseCSV(text);
    state.data.industry = csvToGeoJSON(rows, 'latitude', 'longitude');
    state.loaded.industry = true;
  } else {
    missingFiles.push('industry_sites.csv');
  }

  // Healthcare facilities (CSV)
  const healthcareResp = await safeFetch(DATA_PATHS.healthcare);
  if (healthcareResp) {
    const text = await healthcareResp.text();
    const rows = parseCSV(text);
    state.data.healthcare = csvToGeoJSON(rows, 'latitude', 'longitude');
    state.loaded.healthcare = true;

    const monroeYears = state.data.healthcare.features
      .filter(f => (f.properties.county || '').toLowerCase() === CASE_STUDY_CITY.county.toLowerCase())
      .map(f => Number(f.properties.open_year))
      .filter(v => !Number.isNaN(v) && v > 0);

    if (monroeYears.length > 0) {
      state.caseStudyFirstHealthcareYear = Math.min(...monroeYears);
    } else {
      state.caseStudyFirstHealthcareYear = 1840;
    }
  } else {
    missingFiles.push('healthcare_clean.csv');
  }

  // Demographics (GeoJSON)
  const demResp = await safeFetch(DATA_PATHS.demographics);
  if (demResp) {
    state.data.demographics = await demResp.json();
    computeChoroplethStats(state.data.demographics);
    state.loaded.demographics = true;
  } else {
    missingFiles.push('demographics.geojson');
  }

  // Canal corridor (GeoJSON)
  const canalResp = await safeFetch(DATA_PATHS.canal);
  if (canalResp) {
    state.data.canal = await canalResp.json();
    state.loaded.canal = true;
  } else {
    missingFiles.push('canal_corridor.geojson');
  }

  if (missingFiles.length > 0) {
    showDataBanner(
      `Missing data file(s): ${missingFiles.join(', ')}. ` +
      'Run <code>python scripts/prepare_data.py</code> to generate them.'
    );
  }
}

// ── 6. Choropleth statistics ──────────────────────────────────────────────────

/** Compute quartile breakpoints for each demographic field. */
function computeChoroplethStats(geojson) {
  for (const field of Object.keys(CHOROPLETH_CONFIG)) {
    const vals = geojson.features
      .map(f => f.properties[field])
      .filter(v => v != null && !isNaN(v) && v > 0)
      .sort((a, b) => a - b);

    if (vals.length < 4) continue;

    const q = frac => vals[Math.min(Math.floor(frac * vals.length), vals.length - 1)];

    state.choroplethStats[field] = {
      min: vals[0],
      q1:  q(0.25),
      q2:  q(0.50),
      q3:  q(0.75),
      max: vals[vals.length - 1]
    };
  }
}

/** Build a Mapbox `step` expression that maps a numeric property to 5 colors. */
function makeChoroplethPaint(field) {
  const stats  = state.choroplethStats[field];
  const colors = CHOROPLETH_CONFIG[field].colors;

  if (!stats) return '#cccccc';

  // Ensure stops are strictly increasing (data may be sparse)
  const stops = [stats.q1, stats.q2, stats.q3, stats.max];
  for (let i = 1; i < stops.length; i++) {
    if (stops[i] <= stops[i - 1]) stops[i] = stops[i - 1] + 0.001;
  }

  return [
    'step',
    ['coalesce', ['to-number', ['get', field]], 0],
    colors[0],
    stops[0], colors[1],
    stops[1], colors[2],
    stops[2], colors[3],
    stops[3], colors[4]
  ];
}

// ── 7. Mapbox color match helpers ─────────────────────────────────────────────

/**
 * Build a Mapbox `match` expression that maps a string property to a color.
 * colorMap: { 'value': '#rrggbb', ... }  |  defaultColor: fallback hex
 */
function makeMatchColor(property, colorMap, defaultColor) {
  const expr = ['match', ['downcase', ['coalesce', ['get', property], '']]];
  for (const [key, color] of Object.entries(colorMap)) {
    expr.push(key, color);
  }
  expr.push(defaultColor);
  return expr;
}

// ── 8. Layer setup ────────────────────────────────────────────────────────────

function addSource(id, data) {
  if (!map.getSource(id)) {
    map.addSource(id, { type: 'geojson', data });
  }
}

function initLayers() {
  // ── Canal corridor — always visible blue line ──────────────────────
  if (state.data.canal) {
    addSource('canal', state.data.canal);
    map.addLayer({
      id:     'canal-line',
      type:   'line',
      source: 'canal',
      paint: {
        'line-color':   '#4a90d9',
        'line-width':   2.5,
        'line-opacity': 0.65
      }
    });
  }

  // ── Demographics choropleth — Healthcare mode only ─────────────────
  if (state.data.demographics) {
    addSource('demographics', state.data.demographics);
    map.addLayer({
      id:     'demographics-fill',
      type:   'fill',
      source: 'demographics',
      paint: {
        'fill-color':   makeChoroplethPaint(state.choroplethField),
        'fill-opacity': 0.52
      },
      layout: { visibility: 'none' }
    });
    map.addLayer({
      id:     'demographics-outline',
      type:   'line',
      source: 'demographics',
      paint: { 'line-color': '#aaa', 'line-width': 0.4, 'line-opacity': 0.4 },
      layout: { visibility: 'none' }
    });
  }

  // ── Industry sites — full corridor (Industry mode) ─────────────────
  if (state.data.industry) {
    addSource('industry', state.data.industry);
    map.addLayer({
      id:     'industry-circles',
      type:   'circle',
      source: 'industry',
      paint: {
        'circle-radius':       8,
        'circle-color':        makeMatchColor('industry_type', INDUSTRY_COLORS, '#bdc3c7'),
        'circle-stroke-width': 1.5,
        'circle-stroke-color': '#fff',
        'circle-opacity':      0.92
      }
    });
  }

  // ── Healthcare facilities — full corridor (Healthcare mode) ──────────
  if (state.data.healthcare) {
    addSource('healthcare', state.data.healthcare);
    map.addLayer({
      id:     'healthcare-circles',
      type:   'circle',
      source: 'healthcare',
      paint: {
        'circle-radius':  6,
        'circle-color':   makeMatchColor('facility_type', HEALTHCARE_COLORS, '#7f8c8d'),
        'circle-opacity': 0.88
      },
      layout: { visibility: 'none' }
    });
  }

  // ── Case Study: Rochester-only pre-filtered layers ───────────────────
  // Pre-filtering in JS (not via Mapbox filter expressions) is simpler and
  // more reliable — no type-coercion issues on numeric lat/lng properties.
  const [csW, csS, csE, csN] = CASE_STUDY_CITY.bbox;

  if (state.data.industry) {
    const rochesterIndustry = {
      type: 'FeatureCollection',
      features: state.data.industry.features.filter(f => {
        const [lng, lat] = f.geometry.coordinates;
        return lng >= csW && lng <= csE && lat >= csS && lat <= csN;
      })
    };
    addSource('cs-industry', rochesterIndustry);
    map.addLayer({
      id:     'cs-industry-circles',
      type:   'circle',
      source: 'cs-industry',
      paint: {
        'circle-radius':       9,
        'circle-color':        CS_INDUSTRY_COLOR,
        'circle-stroke-width': 2,
        'circle-stroke-color': '#fff',
        'circle-opacity':      0.92
      },
      layout: { visibility: 'none' }
    });
  }

  if (state.data.healthcare) {
    const rochesterHealthcare = {
      type: 'FeatureCollection',
      features: state.data.healthcare.features.filter(f =>
        (f.properties.county || '').toLowerCase() === CASE_STUDY_CITY.county.toLowerCase()
      )
    };
    addSource('cs-healthcare', rochesterHealthcare);
    map.addLayer({
      id:     'cs-healthcare-circles',
      type:   'circle',
      source: 'cs-healthcare',
      paint: {
        'circle-radius':       7,
        'circle-color':        CS_HEALTHCARE_COLOR,
        'circle-stroke-width': 1.5,
        'circle-stroke-color': '#fff',
        'circle-opacity':      0.88
      },
      layout: { visibility: 'none' }
    });
  }

  // Wire up hover / click interactions now that layers exist
  initMapEvents();

  // Apply mode visibility, year filter, and legend
  applyMode(state.mode, /* skipReset */ true);
}

// ── 9. Mode switching ─────────────────────────────────────────────────────────

/** Show/hide layers appropriate for the given mode; optionally reset view. */
function applyMode(mode, skipReset) {
  state.mode = mode;

  const show = (id, visible) => {
    if (map.getLayer(id)) {
      map.setLayoutProperty(id, 'visibility', visible ? 'visible' : 'none');
    }
  };

  const isIndustry   = mode === 'industry';
  const isHealthcare = mode === 'healthcare';
  const isCaseStudy  = mode === 'casestudy';

  // Main corridor layers
  show('industry-circles',     isIndustry);
  show('demographics-fill',    isHealthcare);
  show('demographics-outline', isHealthcare);
  show('healthcare-circles',   isHealthcare);

  // Case Study: Rochester-only pre-filtered layers
  show('cs-industry-circles',  isCaseStudy);
  show('cs-healthcare-circles',isCaseStudy);

  // Timeline panel: use style.display so it cannot be overridden by cache.
  // Hidden in Healthcare — open_year field is largely absent from the NYS dataset.
  document.getElementById('timeline-panel').style.display =
    isHealthcare ? 'none' : '';

  // Overlay controls — mutually exclusive
  document.getElementById('healthcare-controls').style.display =
    isHealthcare ? '' : 'none';
  document.getElementById('casestudy-controls').style.display =
    isCaseStudy ? '' : 'none';
  document.getElementById('casestudy-stats').style.display =
    isCaseStudy ? '' : 'none';
  document.getElementById('casestudy-zoom-label').style.display =
    isCaseStudy ? '' : 'none';

  // Sync tab buttons
  document.querySelectorAll('.tab-btn').forEach(btn => {
    const active = btn.dataset.mode === mode;
    btn.classList.toggle('active', active);
    btn.setAttribute('aria-selected', String(active));
  });

  applyFilter();
  updateLegend();
  if (isCaseStudy) {
    state.caseStudyZoomedToMill = false;
    adjustCaseStudyZoom();
  } else if (!skipReset) resetMapView();
}

// ── 10. Timeline filter ───────────────────────────────────────────────────────

/** Re-apply the year filter to the currently-visible layers. */
function applyFilter() {
  const yr   = state.year;
  const mode = state.mode;

  // ── Industry timeline filter (used in Industry + Case Study) ───────
  // active_end_year "" → to-number → 0 = "no end date" sentinel.
  const timelineFilter = [
    'all',
    ['<=', ['coalesce', ['to-number', ['get', 'active_start_year']], 9999], yr],
    ['any',
      ['==', ['coalesce', ['to-number', ['get', 'active_end_year']], 0], 0],
      ['>=', ['coalesce', ['to-number', ['get', 'active_end_year']], 0], yr]
    ]
  ];

  // Industry: timeline filter (both corridor and case study layers)
  if (map.getLayer('industry-circles')) {
    map.setFilter('industry-circles', timelineFilter);
  }
  // cs-industry-circles is already spatially filtered to Rochester —
  // only the timeline dimension needs updating here.
  if (map.getLayer('cs-industry-circles')) {
    map.setFilter('cs-industry-circles', timelineFilter);
  }

  // Healthcare corridor: no timeline filter (open_year largely absent for full dataset)
  if (map.getLayer('healthcare-circles')) {
    map.setFilter('healthcare-circles', null);
  }
  // Case Study healthcare: only show facilities with a verified open_year that
  // is <= the selected year. Facilities with no open_year are hidden entirely
  // (to-number("") = 0; the first clause filters those out).
  if (map.getLayer('cs-healthcare-circles')) {
    map.setFilter('cs-healthcare-circles', [
      'all',
      ['>', ['coalesce', ['to-number', ['get', 'open_year']], 0], 0],
      ['<=', ['to-number', ['get', 'open_year']], yr]
    ]);
  }

  if (mode === 'casestudy') {
    updateCityStats();
    adjustCaseStudyZoom();
  }
}

function adjustCaseStudyZoom() {
  if (state.mode !== 'casestudy') return;
  const firstHealthYear = state.caseStudyFirstHealthcareYear || 1840;
  const shouldZoomMill = state.year < firstHealthYear;

  if (shouldZoomMill && !state.caseStudyZoomedToMill) {
    state.caseStudyZoomedToMill = true;
    document.getElementById('zoom-explanation-text').textContent = 'Zooming to Rochester Flouring Mill';
    document.getElementById('casestudy-zoom-label').classList.remove('hidden');
    map.flyTo({ center: CASE_STUDY_CITY.millLocation, zoom: 16, pitch: 45, bearing: 20, duration: 1200 });
  } else if (!shouldZoomMill && state.caseStudyZoomedToMill) {
    state.caseStudyZoomedToMill = false;
    document.getElementById('casestudy-zoom-label').classList.add('hidden');
    map.flyTo({ center: CASE_STUDY_CITY.center, zoom: CASE_STUDY_CITY.zoom, pitch: 0, bearing: 0, duration: 1200 });
  }
}

/** Fly the map to Rochester at city-level zoom. */
function applyCaseStudyCity(skipFly) {
  if (!skipFly) {
    map.flyTo({ center: CASE_STUDY_CITY.center, zoom: CASE_STUDY_CITY.zoom, duration: 900 });
  }
}

/** Update the live stats card for Rochester at the current year. */
function updateCityStats() {
  const yr = state.year;

  // cs-industry source is already spatially filtered to Rochester —
  // just count which sites pass the timeline test.
  let industryCount = 0;
  if (state.data.industry) {
    const [csW, csS, csE, csN] = CASE_STUDY_CITY.bbox;
    industryCount = state.data.industry.features.filter(f => {
      const [lng, lat] = f.geometry.coordinates;
      if (lng < csW || lng > csE || lat < csS || lat > csN) return false;
      const p     = f.properties;
      const start = Number(p.active_start_year) || 9999;
      const end   = Number(p.active_end_year)   || 0;
      return start <= yr && (end <= 0 || end >= yr);
    }).length;
  }

  // cs-healthcare is Monroe County only; only count facilities with a verified
  // open_year (open_year > 0) that is <= the selected year.
  let healthcareCount = 0;
  if (state.data.healthcare) {
    healthcareCount = state.data.healthcare.features.filter(f => {
      if ((f.properties.county || '').toLowerCase() !== CASE_STUDY_CITY.county.toLowerCase()) return false;
      const openYr = Number(f.properties.open_year) || 0;
      return openYr > 0 && openYr <= yr;
    }).length;
  }

  document.getElementById('stat-year').textContent     = yr;
  document.getElementById('stat-industry').textContent = industryCount;
  document.getElementById('stat-healthcare').textContent = healthcareCount;
}

/** Return a display string for active_end_year — 'present' when empty/0/9999. */
function fmtEndYear(val) {
  const n = Number(val);
  return (!val || n <= 0 || n >= 9999) ? 'present' : n;
}

// ── 11. Map interactions (hover + click) ──────────────────────────────────────

function initMapEvents() {
  // ── Industry: hover ────────────────────────────────────────────────
  map.on('mousemove', 'industry-circles', e => {
    if (!e.features.length) return;
    const p = e.features[0].properties;
    const end = fmtEndYear(p.active_end_year);
    showTooltip(
      e.originalEvent.clientX, e.originalEvent.clientY,
      `<strong>${p.site_name}</strong>` +
      `<em>${p.industry_type}</em>` +
      `${p.town || ''}<br>${p.active_start_year || '?'} – ${end}`
    );
    map.getCanvas().style.cursor = 'pointer';
  });
  map.on('mouseleave', 'industry-circles', () => {
    hideTooltip();
    map.getCanvas().style.cursor = '';
  });

  // ── Industry: click → draggable panel ──────────────────────────────
  map.on('click', 'industry-circles', e => {
    if (!e.features.length) return;
    const p   = e.features[0].properties;
    const end = fmtEndYear(p.active_end_year);
    showDetailPanel(p.site_name, `
      <table>
        <tr><th>Industry</th><td style="text-transform:capitalize">${p.industry_type || '—'}</td></tr>
        <tr><th>Town</th><td>${p.town || '—'}</td></tr>
        <tr><th>Active</th><td>${p.active_start_year || '?'} – ${end}</td></tr>
      </table>
      ${p.description ? `<p class="detail-description">${p.description}</p>` : ''}
    `);
    map.flyTo({ center: e.lngLat, zoom: 16, duration: 800 });
  });

  // ── Healthcare: hover ──────────────────────────────────────────────
  map.on('mousemove', 'healthcare-circles', e => {
    if (!e.features.length) return;
    const p = e.features[0].properties;
    showTooltip(
      e.originalEvent.clientX, e.originalEvent.clientY,
      `<strong>${p.facility_name}</strong>` +
      `<em>${p.facility_type}</em>` +
      `${p.county ? p.county + ' County' : ''}`
    );
    map.getCanvas().style.cursor = 'pointer';
  });
  map.on('mouseleave', 'healthcare-circles', () => {
    hideTooltip();
    map.getCanvas().style.cursor = '';
  });

  // ── Healthcare: click → draggable panel ────────────────────────────
  map.on('click', 'healthcare-circles', e => {
    if (!e.features.length) return;
    const p    = e.features[0].properties;
    const demHtml = getDemographicContext(e.lngLat);
    showDetailPanel(p.facility_name, `
      <table>
        <tr><th>Type</th><td style="text-transform:capitalize">${p.facility_type || '—'}</td></tr>
        <tr><th>County</th><td>${p.county ? p.county + ' County' : '—'}</td></tr>
        <tr><th>Opened</th><td>${p.open_year || 'Unknown'}</td></tr>
      </table>
      ${demHtml}
    `);
    map.flyTo({ center: e.lngLat, zoom: 16, duration: 800 });
  });

  // ── Case Study Rochester layers — reuse same tooltip/panel logic ────
  for (const id of ['cs-industry-circles', 'cs-healthcare-circles']) {
    const isInd = id.startsWith('cs-industry');

    map.on('mousemove', id, e => {
      if (!e.features.length) return;
      const p = e.features[0].properties;
      if (isInd) {
        const end = fmtEndYear(p.active_end_year);
        showTooltip(e.originalEvent.clientX, e.originalEvent.clientY,
          `<strong>${p.site_name}</strong><em>${p.industry_type}</em>${p.town || ''}<br>${p.active_start_year || '?'} – ${end}`);
      } else {
        showTooltip(e.originalEvent.clientX, e.originalEvent.clientY,
          `<strong>${p.facility_name}</strong><em>${p.facility_type}</em>${p.county ? p.county + ' County' : ''}`);
      }
      map.getCanvas().style.cursor = 'pointer';
    });

    map.on('mouseleave', id, () => { hideTooltip(); map.getCanvas().style.cursor = ''; });

    map.on('click', id, e => {
      if (!e.features.length) return;
      const p = e.features[0].properties;
      if (isInd) {
        const end = fmtEndYear(p.active_end_year);
        showDetailPanel(p.site_name, `
          <table>
            <tr><th>Industry</th><td style="text-transform:capitalize">${p.industry_type || '—'}</td></tr>
            <tr><th>Town</th><td>${p.town || '—'}</td></tr>
            <tr><th>Active</th><td>${p.active_start_year || '?'} – ${end}</td></tr>
          </table>
          ${p.description ? `<p class="detail-description">${p.description}</p>` : ''}`);
      } else {
        showDetailPanel(p.facility_name, `
          <table>
            <tr><th>Type</th><td style="text-transform:capitalize">${p.facility_type || '—'}</td></tr>
            <tr><th>County</th><td>${p.county ? p.county + ' County' : '—'}</td></tr>
            <tr><th>Opened</th><td>${p.open_year || 'Unknown'}</td></tr>
          </table>`);
      }
      map.flyTo({ center: e.lngLat, zoom: 16, duration: 800 });
    });
  }
}

/**
 * Query the rendered demographics layer at a given map coordinate
 * to find the census tract and return an HTML demographics summary.
 */
function getDemographicContext(lngLat) {
  if (!map.getLayer('demographics-fill')) {
    return '<p class="detail-description">No demographic layer loaded.</p>';
  }

  // Temporarily make the layer visible so queryRenderedFeatures works
  // (it only returns features from *rendered* layers)
  const wasHidden = map.getLayoutProperty('demographics-fill', 'visibility') === 'none';
  if (wasHidden) map.setLayoutProperty('demographics-fill', 'visibility', 'visible');

  const pixel    = map.project(lngLat);
  const features = map.queryRenderedFeatures(pixel, { layers: ['demographics-fill'] });

  if (wasHidden) map.setLayoutProperty('demographics-fill', 'visibility', 'none');

  if (!features.length) {
    return '<p class="detail-description">No census tract data for this location.</p>';
  }

  const p = features[0].properties;
  const age  = p.median_age       ? p.median_age.toFixed(1)                                 : 'N/A';
  const inc  = p.median_income     ? '$' + Math.round(p.median_income).toLocaleString()      : 'N/A';
  const dens = p.population_density ? Math.round(p.population_density).toLocaleString() + '/sq mi' : 'N/A';

  return `
    <h4>Census Tract Demographics</h4>
    <table>
      <tr><th>Median Age</th><td>${age}</td></tr>
      <tr><th>Median Income</th><td>${inc}</td></tr>
      <tr><th>Pop. Density</th><td>${dens}</td></tr>
    </table>
  `;
}

// ── 12. Legend ────────────────────────────────────────────────────────────────

function updateLegend() {
  const el = document.getElementById('legend');

  if (state.mode === 'industry') {
    el.innerHTML = `<h4>Industry Type</h4>${colorLegendHTML(INDUSTRY_COLORS)}`;
  } else if (state.mode === 'healthcare') {
    el.innerHTML = `<h4>Facility Type</h4>${colorLegendHTML(HEALTHCARE_COLORS)}`;
    if (state.loaded.demographics) {
      el.innerHTML += choroplethLegendHTML(state.choroplethField);
    }
  } else {
    // Case Study — two categories only; tooltip/panel shows the specific type
    el.innerHTML = `
      <h4>Rochester Case Study</h4>
      <div class="legend-item">
        <span class="legend-dot" style="background:${CS_INDUSTRY_COLOR}"></span>
        <span>Industry site</span>
      </div>
      <div class="legend-item">
        <span class="legend-dot" style="background:${CS_HEALTHCARE_COLOR}"></span>
        <span>Healthcare facility</span>
      </div>
      <p style="font-size:11px;color:#999;margin-top:8px;line-height:1.4">
        Drag the slider to watch Rochester evolve.<br>
        Only historically documented facilities shown.<br>
        Hover or click any dot for details.
      </p>`;
  }
}

function colorLegendHTML(colorMap) {
  return Object.entries(colorMap)
    .map(([type, color]) => `
      <div class="legend-item">
        <span class="legend-dot" style="background:${color}"></span>
        <span>${type}</span>
      </div>`)
    .join('');
}

function choroplethLegendHTML(field) {
  const cfg   = CHOROPLETH_CONFIG[field];
  const stats = state.choroplethStats[field];
  if (!stats) return '';

  const gradient  = `linear-gradient(to right, ${cfg.colors.join(', ')})`;
  const minLabel  = formatDemValue(field, stats.min);
  const maxLabel  = formatDemValue(field, stats.max);

  return `
    <h4>${cfg.label}</h4>
    <div class="choropleth-bar-wrap">
      <div class="choropleth-gradient-bar" style="background:${gradient}"></div>
      <div class="choropleth-range-labels">
        <span>${minLabel}</span><span>${maxLabel}</span>
      </div>
    </div>`;
}

function formatDemValue(field, val) {
  if (val == null || isNaN(val)) return 'N/A';
  if (field === 'median_income')    return '$' + Math.round(val).toLocaleString();
  if (field === 'population_density') return Math.round(val).toLocaleString();
  return parseFloat(val).toFixed(1);
}

// ── 13. Tooltip ───────────────────────────────────────────────────────────────

const tooltipEl = document.getElementById('tooltip');

function showTooltip(clientX, clientY, html) {
  tooltipEl.innerHTML = html;
  tooltipEl.classList.remove('hidden');

  // Position near cursor, prevent viewport overflow
  const W = window.innerWidth, H = window.innerHeight;
  const TW = 220, TH = 90, OFFSET = 14;
  let left = clientX + OFFSET;
  let top  = clientY + OFFSET;
  if (left + TW  > W) left = clientX - TW  - OFFSET;
  if (top  + TH  > H) top  = clientY - TH  - OFFSET;

  tooltipEl.style.left = `${left}px`;
  tooltipEl.style.top  = `${top}px`;
}

function hideTooltip() {
  tooltipEl.classList.add('hidden');
}

// ── 14. Draggable detail panel ────────────────────────────────────────────────

const detailPanel = document.getElementById('detail-panel');

function showDetailPanel(title, html) {
  document.getElementById('detail-panel-title').textContent = title;
  document.getElementById('detail-panel-content').innerHTML = html;
  detailPanel.classList.remove('hidden');
  // Reset to default right-side position whenever opened
  detailPanel.style.left  = '';
  detailPanel.style.right = '20px';
  detailPanel.style.top   = '70px';
}

function closeDetailPanel() {
  detailPanel.classList.add('hidden');
}

function initDragPanel() {
  const header = document.getElementById('detail-panel-header');
  let dragging = false, ox = 0, oy = 0;

  header.addEventListener('mousedown', e => {
    if (e.button !== 0) return;
    const rect = detailPanel.getBoundingClientRect();
    // Switch to left-anchored coordinates
    detailPanel.style.right = '';
    detailPanel.style.left  = `${rect.left}px`;
    detailPanel.style.top   = `${rect.top}px`;
    ox = e.clientX - rect.left;
    oy = e.clientY - rect.top;
    dragging = true;
    e.preventDefault();
  });

  document.addEventListener('mousemove', e => {
    if (!dragging) return;
    const l = Math.max(0, Math.min(e.clientX - ox, window.innerWidth  - 50));
    const t = Math.max(0, Math.min(e.clientY - oy, window.innerHeight - 50));
    detailPanel.style.left = `${l}px`;
    detailPanel.style.top  = `${t}px`;
  });

  document.addEventListener('mouseup', () => { dragging = false; });

  document.getElementById('detail-panel-close').addEventListener('click', closeDetailPanel);
}

// ── 15. UI event wiring ───────────────────────────────────────────────────────

function initUI() {
  // Tab buttons
  document.querySelectorAll('.tab-btn').forEach(btn => {
    btn.addEventListener('click', () => applyMode(btn.dataset.mode));
  });

  // Timeline slider
  const slider       = document.getElementById('timeline-slider');
  const yearDisplay  = document.getElementById('current-year-display');

  slider.value = String(state.year);
  yearDisplay.textContent = String(state.year);

  slider.addEventListener('input', () => {
    state.year = parseInt(slider.value, 10);
    yearDisplay.textContent = String(state.year);
    applyFilter();
  });

  // Choropleth field dropdown
  document.getElementById('choropleth-field').addEventListener('change', e => {
    state.choroplethField = e.target.value;
    if (map.getLayer('demographics-fill')) {
      map.setPaintProperty('demographics-fill', 'fill-color', makeChoroplethPaint(state.choroplethField));
    }
    updateLegend();
  });

  initStory();
  initDragPanel();
}

// ── 16. Map view reset ────────────────────────────────────────────────────────

function resetMapView() {
  map.flyTo({ center: CONFIG.center, zoom: CONFIG.zoom, duration: 600 });
}

// ── 17. Data error banner ─────────────────────────────────────────────────────

function showDataBanner(message) {
  const el = document.getElementById('data-banner');
  el.innerHTML = message;
  el.classList.remove('hidden');
  // Auto-dismiss after 12 s
  setTimeout(() => el.classList.add('hidden'), 12000);
}

// ── 18. Bootstrap ─────────────────────────────────────────────────────────────

let mapStyleReady = false;
let dataReady     = false;

map.on('load', () => {
  mapStyleReady = true;
  if (dataReady) initLayers();
});

(async () => {
  initUI();
  await loadAllData();
  dataReady = true;
  if (mapStyleReady) initLayers();
})();
